version: "3.8"

services:
  db: &db
    image: mysql:8.0
    environment: 
      MYSQL_ROOT_PASSWORD: password
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - mysql-data:/var/lib/mysql

  web:
    container_name: web
    image: web
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./web:/usr/web
    ports:
      - "3000:3000"
    environment:
      STATEMENT_API_HOST: http://host.docker.internal:3001
      STATEMENT_API_USERNAME: API_USER
      STATEMENT_API_PASSWORD: password
    depends_on:
      - db

volumes:
  bundle:
  mysql-data: 
    driver: local
